// Code generated by protoc-gen-go.
// source: mmo.proto
// DO NOT EDIT!

/*
Package xymmopb is a generated protocol buffer package.

It is generated from these files:
	mmo.proto

It has these top-level messages:
	Map
	Player
	Coordinate
	Action
	Msg_S_Uid
	Msg_C_Start
	Msg_S_GameStart
	Msg_CS_Action
	Msg_CS_Ping
	Msg_S_GameOver
*/
package xymmopb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type CMD_CODE int32

const (
	CMD_CODE_CMD_S_GenerateUid CMD_CODE = 0
	CMD_CODE_CMD_C_Start       CMD_CODE = 1
	CMD_CODE_CMD_S_GameStart   CMD_CODE = 2
	CMD_CODE_CMD_C_Action      CMD_CODE = 3
	CMD_CODE_CMD_S_Action      CMD_CODE = 4
	CMD_CODE_CMD_S_GameOver    CMD_CODE = 5
	CMD_CODE_CMD_C_PING        CMD_CODE = 6
	CMD_CODE_CMD_S_PING        CMD_CODE = 7
)

var CMD_CODE_name = map[int32]string{
	0: "CMD_S_GenerateUid",
	1: "CMD_C_Start",
	2: "CMD_S_GameStart",
	3: "CMD_C_Action",
	4: "CMD_S_Action",
	5: "CMD_S_GameOver",
	6: "CMD_C_PING",
	7: "CMD_S_PING",
}
var CMD_CODE_value = map[string]int32{
	"CMD_S_GenerateUid": 0,
	"CMD_C_Start":       1,
	"CMD_S_GameStart":   2,
	"CMD_C_Action":      3,
	"CMD_S_Action":      4,
	"CMD_S_GameOver":    5,
	"CMD_C_PING":        6,
	"CMD_S_PING":        7,
}

func (x CMD_CODE) Enum() *CMD_CODE {
	p := new(CMD_CODE)
	*p = x
	return p
}
func (x CMD_CODE) String() string {
	return proto.EnumName(CMD_CODE_name, int32(x))
}
func (x *CMD_CODE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMD_CODE_value, data, "CMD_CODE")
	if err != nil {
		return err
	}
	*x = CMD_CODE(value)
	return nil
}

type Direction int32

const (
	Direction_Idle  Direction = 0
	Direction_UP    Direction = 1
	Direction_DOWN  Direction = 2
	Direction_LEFT  Direction = 3
	Direction_RIGHT Direction = 4
)

var Direction_name = map[int32]string{
	0: "Idle",
	1: "UP",
	2: "DOWN",
	3: "LEFT",
	4: "RIGHT",
}
var Direction_value = map[string]int32{
	"Idle":  0,
	"UP":    1,
	"DOWN":  2,
	"LEFT":  3,
	"RIGHT": 4,
}

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}
func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}
func (x *Direction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Direction_value, data, "Direction")
	if err != nil {
		return err
	}
	*x = Direction(value)
	return nil
}

type Map struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Map) Reset()         { *m = Map{} }
func (m *Map) String() string { return proto.CompactTextString(m) }
func (*Map) ProtoMessage()    {}

func (m *Map) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type Player struct {
	Uid              *uint32 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}

func (m *Player) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

type Coordinate struct {
	X                *int32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}

func (m *Coordinate) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Coordinate) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type Action struct {
	Player           *Player     `protobuf:"bytes,1,req,name=player" json:"player,omitempty"`
	Timestamp        *int64      `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	Direction        *Direction  `protobuf:"varint,3,opt,name=direction,enum=xymmopb.Direction" json:"direction,omitempty"`
	Ccoordinate      *Coordinate `protobuf:"bytes,4,opt" json:"Ccoordinate,omitempty"`
	Tcoordinate      *Coordinate `protobuf:"bytes,5,opt" json:"Tcoordinate,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}

func (m *Action) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *Action) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Action) GetDirection() Direction {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return Direction_Idle
}

func (m *Action) GetCcoordinate() *Coordinate {
	if m != nil {
		return m.Ccoordinate
	}
	return nil
}

func (m *Action) GetTcoordinate() *Coordinate {
	if m != nil {
		return m.Tcoordinate
	}
	return nil
}

// 服务端uid生成消息
type Msg_S_Uid struct {
	Uid              *uint32 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Msg_S_Uid) Reset()         { *m = Msg_S_Uid{} }
func (m *Msg_S_Uid) String() string { return proto.CompactTextString(m) }
func (*Msg_S_Uid) ProtoMessage()    {}

func (m *Msg_S_Uid) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

// 客户端开始消息
type Msg_C_Start struct {
	Player           *Player `protobuf:"bytes,1,req,name=player" json:"player,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Msg_C_Start) Reset()         { *m = Msg_C_Start{} }
func (m *Msg_C_Start) String() string { return proto.CompactTextString(m) }
func (*Msg_C_Start) ProtoMessage()    {}

func (m *Msg_C_Start) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

// 服务端游戏开始消息
type Msg_S_GameStart struct {
	Map              *Map      `protobuf:"bytes,1,opt,name=map" json:"map,omitempty"`
	Time             *uint64   `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Timedelay        *uint64   `protobuf:"varint,3,opt,name=timedelay" json:"timedelay,omitempty"`
	Players          []*Player `protobuf:"bytes,4,rep,name=players" json:"players,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Msg_S_GameStart) Reset()         { *m = Msg_S_GameStart{} }
func (m *Msg_S_GameStart) String() string { return proto.CompactTextString(m) }
func (*Msg_S_GameStart) ProtoMessage()    {}

func (m *Msg_S_GameStart) GetMap() *Map {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *Msg_S_GameStart) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Msg_S_GameStart) GetTimedelay() uint64 {
	if m != nil && m.Timedelay != nil {
		return *m.Timedelay
	}
	return 0
}

func (m *Msg_S_GameStart) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

// 动作消息
type Msg_CS_Action struct {
	Actions          []*Action `protobuf:"bytes,1,rep,name=actions" json:"actions,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Msg_CS_Action) Reset()         { *m = Msg_CS_Action{} }
func (m *Msg_CS_Action) String() string { return proto.CompactTextString(m) }
func (*Msg_CS_Action) ProtoMessage()    {}

func (m *Msg_CS_Action) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

// ping消息
type Msg_CS_Ping struct {
	Time             *uint64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Msg_CS_Ping) Reset()         { *m = Msg_CS_Ping{} }
func (m *Msg_CS_Ping) String() string { return proto.CompactTextString(m) }
func (*Msg_CS_Ping) ProtoMessage()    {}

func (m *Msg_CS_Ping) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

// 游戏结束
type Msg_S_GameOver struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Msg_S_GameOver) Reset()         { *m = Msg_S_GameOver{} }
func (m *Msg_S_GameOver) String() string { return proto.CompactTextString(m) }
func (*Msg_S_GameOver) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("xymmopb.CMD_CODE", CMD_CODE_name, CMD_CODE_value)
	proto.RegisterEnum("xymmopb.Direction", Direction_name, Direction_value)
}
